version: '3'

services:
  api:
#    build: ./
    image: rsmdk/nestjs:0.0.1
    container_name: nestjs_mongodb
    ports:
      - '${PORT}:${PORT}'
#    depends_on:
#      - database
    networks:
      - nestjs-network

#  database:
#    image: mongo
#    container_name: mongo_db
#    volumes:
#      - './mongodb-backup:/data/db'
#    networks:
#      - nestjs-network

networks:
  nestjs-network:
    driver: bridge
