version: '3'

services:
  api:
    build: ./
    container_name: nestjs_mongodb
    ports:
      - '3000:3000'
    depends_on:
      - database
    networks:
      - nestjs-network

#  database:
#    image: mongo
#    container_name: mongo_db
#    volumes:
#      - './mongodb-backup:/data/db'
#    networks:
#      - nestjs-network

networks:
  nestjs-network:
    driver: bridge
